### PR TITLE
chore: Cherry-pick key commits for supporting v1 features in v2 API

### PR DESCRIPTION
**Pull request by rimolive**
**Description of your changes:**
Resolves [RHOAIENG-4711](https://issues.redhat.com/browse/RHOAIENG-4711)

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by dsp-developers** [comment]
A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-31`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-31`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-31`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-31`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-31`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-31`

**Comment by dsp-developers** [comment]
An OCP cluster where you are logged in as cluster admin is required.

The Data Science Pipelines team recommends testing this using the Data Science Pipelines Operator.  Check [here](https://github.com/opendatahub-io/data-science-pipelines-operator) for more information on using the DSPO.

To use and deploy a DSP stack with these images (assuming the DSPO is deployed), first save the following YAML to a file named `dspa.pr-31.yaml`:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pr-31
spec:
  dspVersion: v2
  apiServer:
    image: "quay.io/opendatahub/ds-pipelines-api-server:pr-31"
    argoDriverImage: "quay.io/opendatahub/ds-pipelines-driver:pr-31"
    argoLauncherImage: "quay.io/opendatahub/ds-pipelines-launcher:pr-31"
  persistenceAgent:
    image: "quay.io/opendatahub/ds-pipelines-persistenceagent:pr-31"
  scheduledWorkflow:
    image: "quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-31"
  mlmd:  
    deploy: true  # Optional component
    grpc:
      image: "quay.io/opendatahub/mlmd-grpc-server:latest"
    envoy:
      image: "registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2"
  mlpipelineUI:
    deploy: true  # Optional component 
    image: "quay.io/opendatahub/ds-pipelines-frontend:pr-31"
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```

Then run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines.git
cd data-science-pipelines/
git fetch origin pull/31/head
git checkout -b pullrequest ebe49d004380837a964984122b6c1d301679f824
oc apply -f dspa.pr-31.yaml
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-31`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-31`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-31`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-31`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-31`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-31`

**Comment by DharmitD** [comment]
cross verified with all PRs mentioned in https://issues.redhat.com/browse/RHOAIENG-4711
Made sure all commits are cherry picked in this PR.

/lgtm

**Review by DharmitD — COMMENTED** [review]
cross verified with all PRs mentioned in https://issues.redhat.com/browse/RHOAIENG-4711
Made sure all commits are cherry picked in this PR.

/lgtm

**Comment by DharmitD** [comment]
Deployed the changes, spun up a pipeline and created a run successfully.

Screenshot from 2024-04-02 12-53-10

**Pull request merged**
