### PR TITLE
UPSTREAM: <carry>: Added cached layer for Go dependencies to Dockerfiles

### PR DESCRIPTION
**Pull request by hbelmiro**
**Description of your changes:**
This PR modifies the Dockerfiles to download dependencies earlier. That way the download layers can be cached and subsequent builds will be faster when dependencies don't change.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by dsp-developers** [comment]
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 1 commits between e27b68731776c35efe5e363295c3cc4a782cec4f...142df824abecffeb613bf14a17d6e4dc5548bcab
```

**Comment by dsp-developers** [comment]
A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-111`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-111`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-111`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-111`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-111`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-111`

**Comment by dsp-developers** [comment]
An OCP cluster where you are logged in as cluster admin is required.

The Data Science Pipelines team recommends testing this using the Data Science Pipelines Operator.  Check [here](https://github.com/opendatahub-io/data-science-pipelines-operator) for more information on using the DSPO.

To use and deploy a DSP stack with these images (assuming the DSPO is deployed), first save the following YAML to a file named `dspa.pr-111.yaml`:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pr-111
spec:
  dspVersion: v2
  apiServer:
    image: "quay.io/opendatahub/ds-pipelines-api-server:pr-111"
    argoDriverImage: "quay.io/opendatahub/ds-pipelines-driver:pr-111"
    argoLauncherImage: "quay.io/opendatahub/ds-pipelines-launcher:pr-111"
  persistenceAgent:
    image: "quay.io/opendatahub/ds-pipelines-persistenceagent:pr-111"
  scheduledWorkflow:
    image: "quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-111"
  mlmd:  
    deploy: true  # Optional component
    grpc:
      image: "quay.io/opendatahub/mlmd-grpc-server:latest"
    envoy:
      image: "registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2"
  mlpipelineUI:
    deploy: true  # Optional component 
    image: "quay.io/opendatahub/ds-pipelines-frontend:pr-111"
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```

Then run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines.git
cd data-science-pipelines/
git fetch origin pull/111/head
git checkout -b pullrequest 142df824abecffeb613bf14a17d6e4dc5548bcab
oc apply -f dspa.pr-111.yaml
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by gregsheremeta** [comment]
why not do this in kubeflow/pipelines first?

**Comment by hbelmiro** [comment]
> why not do this in kubeflow/pipelines first?

@gregsheremeta [I did](https://github.com/kubeflow/pipelines/pull/11348). But Kubeflow's Dockerfiles are a bit different than DSP's.

**Comment by dsp-developers** [comment]
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
```
commitchecker verson unknown
Validating 0 commits between 7c3b0204f09934458ccd7ce65deba74fb0146286...142df824abecffeb613bf14a17d6e4dc5548bcab
```

**Pull request merged**
