### PR TITLE
UPSTREAM:<carry>:chore:RHOAIENG-7423 - Updated ubi8 image and go-toolset version

### PR DESCRIPTION
**Pull request by amadhusu**
**Description of your changes:**
Updated ubi8 image as suggested in [RHOAIENG-7423](https://issues.redhat.com//browse/RHOAIENG-7423)

**Testing instructions:**
Sanity Tests

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by dsp-developers** [comment]
A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-44`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-44`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-44`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-44`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-44`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-44`

**Comment by dsp-developers** [comment]
An OCP cluster where you are logged in as cluster admin is required.

The Data Science Pipelines team recommends testing this using the Data Science Pipelines Operator.  Check [here](https://github.com/opendatahub-io/data-science-pipelines-operator) for more information on using the DSPO.

To use and deploy a DSP stack with these images (assuming the DSPO is deployed), first save the following YAML to a file named `dspa.pr-44.yaml`:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pr-44
spec:
  dspVersion: v2
  apiServer:
    image: "quay.io/opendatahub/ds-pipelines-api-server:pr-44"
    argoDriverImage: "quay.io/opendatahub/ds-pipelines-driver:pr-44"
    argoLauncherImage: "quay.io/opendatahub/ds-pipelines-launcher:pr-44"
  persistenceAgent:
    image: "quay.io/opendatahub/ds-pipelines-persistenceagent:pr-44"
  scheduledWorkflow:
    image: "quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-44"
  mlmd:  
    deploy: true  # Optional component
    grpc:
      image: "quay.io/opendatahub/mlmd-grpc-server:latest"
    envoy:
      image: "registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2"
  mlpipelineUI:
    deploy: true  # Optional component 
    image: "quay.io/opendatahub/ds-pipelines-frontend:pr-44"
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```

Then run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines.git
cd data-science-pipelines/
git fetch origin pull/44/head
git checkout -b pullrequest ebb1b7d4d164dcb99fa5eeeeca1f65cd816301f4
oc apply -f dspa.pr-44.yaml
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by HumairAK** [comment]
@amadhusu can you remove the jira id from the commit message?

**Comment by dsp-developers** [comment]
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
commitchecker verson unknown
ERROR: couldn't find commits from 25f33aa32f99ff377ef6972a8f4dc9e8c309fb07..ea1278301446611dfa18003ebaf8c6c71be37da6: error executing git log: fatal: Invalid revision range 25f33aa32f99ff377ef6972a8f4dc9e8c309fb07..ea1278301446611dfa18003ebaf8c6c71be37da6
: exit status 128

**Comment by dsp-developers** [comment]
Change to PR detected. A new PR build was completed.
  A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-44`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-44`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-44`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-44`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-44`
  **MLMD Server**: `quay.io/opendatahub/mlmd-grpc-server:latest`
  **MLMD Envoy Proxy**: `registry.redhat.io/openshift-service-mesh/proxyv2-rhel8:2.3.9-2`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-44`

**Comment by dsp-developers** [comment]
### Commit Checker results:

```
**NOTE**: These are the results of the commit checker scans. 
If these are not commits from upstream kfp, then please ensure
you adhere to the commit checker formatting
```
commitchecker verson unknown
ERROR: couldn't find commits from effca01ddbe891dc2f1badfb01f30bf20283f3ef..ea1278301446611dfa18003ebaf8c6c71be37da6: error executing git log: fatal: Invalid revision range effca01ddbe891dc2f1badfb01f30bf20283f3ef..ea1278301446611dfa18003ebaf8c6c71be37da6
: exit status 128

**Pull request merged**
