### PR TITLE
chore: Updated envoy and grpc image URLs for bot

### PR DESCRIPTION
**Pull request by amadhusu**
**Description of your changes:**
Updated envoy and grpc image URLs for bot to comment on PRs.

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by dsp-developers** [comment]
A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-25`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-25`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-25`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-25`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-25`
  **MLMD Server**: `quay.io/opendatahub/ds-pipelines-metadata-grpc:pr-25`
  **MLMD Envoy Proxy**: `quay.io/opendatahub/ds-pipelines-metadata-envoy:pr-25`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-25`

**Comment by dsp-developers** [comment]
An OCP cluster where you are logged in as cluster admin is required.

The Data Science Pipelines team recommends testing this using the Data Science Pipelines Operator.  Check [here](https://github.com/opendatahub-io/data-science-pipelines-operator) for more information on using the DSPO.

To use and deploy a DSP stack with these images (assuming the DSPO is deployed), first save the following YAML to a file named `dspa.pr-25.yaml`:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pr-25
spec:
  dspVersion: v2
  apiServer:
    image: "quay.io/opendatahub/ds-pipelines-api-server:pr-25"
    argoDriverImage: "quay.io/opendatahub/ds-pipelines-driver:pr-25"
    argoLauncherImage: "quay.io/opendatahub/ds-pipelines-launcher:pr-25"
  persistenceAgent:
    image: "quay.io/opendatahub/ds-pipelines-persistenceagent:pr-25"
  scheduledWorkflow:
    image: "quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-25"
  mlmd:  
    deploy: true  # Optional component
    grpc:
      image: "quay.io/opendatahub/ds-pipelines-metadata-grpc:pr-25"
    envoy:
      image: "quay.io/opendatahub/ds-pipelines-metadata-envoy:pr-25"
  mlpipelineUI:
    deploy: true  # Optional component 
    image: "quay.io/opendatahub/ds-pipelines-frontend:pr-25"
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```

Then run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines.git
cd data-science-pipelines/
git fetch origin pull/25/head
git checkout -b pullrequest ff2f239453fc314e76e269b50a5cab6d623ba9c9
oc apply -f dspa.pr-25.yaml
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Comment by gregsheremeta** [comment]
@amadhusu @rimolive are you sure the GRPC one is correct? Pulling and starting gives me an error:
```
ds-pipeline-metadata-grpc-uxdkfpdemo-85bd8c56f7-cltsk
...
Successfully pulled image "quay.io/opendatahub/model-registry:latest" in 179.361789ms (179.37745ms including waiting)
...
Error: container create failed: time="2024-03-12T20:47:27Z" level=error msg="runc create failed: unable to start container process: exec: \"/bin/metadata_store_server\": stat /bin/metadata_store_server: no such file or directory"
```

**Comment by rimolive** [comment]
Well, it should:

https://quay.io/repository/opendatahub/model-registry/tag/latest

**Comment by gregsheremeta** [comment]
Fix: https://github.com/opendatahub-io/data-science-pipelines/pull/26

**Pull request merged**
