### PR TITLE
'UPSTREAM: <carry>' should be the convention followed for commits for carrying patches

### PR DESCRIPTION
**Pull request by amadhusu**
**Description of your changes:**
Resolves [RHOAIENG-1695](https://issues.redhat.com/browse/RHOAIENG-1695)

**Checklist:**
- [X] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by dsp-developers** [comment]
A set of new images have been built to help with testing out this PR: 
  **API Server**: `quay.io/opendatahub/ds-pipelines-api-server:pr-15`
  **DSP DRIVER**: `quay.io/opendatahub/ds-pipelines-driver:pr-15`
  **DSP LAUNCHER**: `quay.io/opendatahub/ds-pipelines-launcher:pr-15`
  **Persistence Agent**: `quay.io/opendatahub/ds-pipelines-persistenceagent:pr-15`
  **Scheduled Workflow Manager**: `quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-15`
  **MLMD Server**: `quay.io/opendatahub/ds-pipelines-metadata-grpc:pr-15`
  **MLMD Envoy Proxy**: `quay.io/opendatahub/ds-pipelines-metadata-envoy:pr-15`
  **UI**: `quay.io/opendatahub/ds-pipelines-frontend:pr-15`

**Comment by dsp-developers** [comment]
An OCP cluster where you are logged in as cluster admin is required.

The Data Science Pipelines team recommends testing this using the Data Science Pipelines Operator.  Check [here](https://github.com/opendatahub-io/data-science-pipelines-operator) for more information on using the DSPO.

To use and deploy a DSP stack with these images (assuming the DSPO is deployed), first save the following YAML to a file named `dspa.pr-15.yaml`:
```yaml
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  name: pr-15
spec:
  dspVersion: v2
  apiServer:
    image: "quay.io/opendatahub/ds-pipelines-api-server:pr-15"
    argoDriverImage: "quay.io/opendatahub/ds-pipelines-driver:pr-15"
    argoLauncherImage: "quay.io/opendatahub/ds-pipelines-launcher:pr-15"
  persistenceAgent:
    image: "quay.io/opendatahub/ds-pipelines-persistenceagent:pr-15"
  scheduledWorkflow:
    image: "quay.io/opendatahub/ds-pipelines-scheduledworkflow:pr-15"
  mlmd:  
    deploy: true  # Optional component
    grpc:
      image: "quay.io/opendatahub/ds-pipelines-metadata-grpc:pr-15"
    envoy:
      image: "quay.io/opendatahub/ds-pipelines-metadata-envoy:pr-15"
  mlpipelineUI:
    deploy: true  # Optional component 
    image: "quay.io/opendatahub/ds-pipelines-frontend:pr-15"
  objectStorage:
    minio:
      deploy: true
      image: 'quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance'
```

Then run the following:

```bash
cd $(mktemp -d)
git clone git@github.com:opendatahub-io/data-science-pipelines.git
cd data-science-pipelines/
git fetch origin pull/15/head
git checkout -b pullrequest b6b2ffe14b7f2e33cdefab701ed80731b32b4295
oc apply -f dspa.pr-15.yaml
```

More instructions [here](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance) on how to deploy and test a Data Science Pipelines Application.

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
/hold

I'd like to avoid having to add carried patches to readme as it introduces unnecessary conflicts. 
@amadhusu did you look into openshift-ci and whether we can utilize it to enforce this pattern via ci?

**Comment by amadhusu** [comment]
Closing out this Pull Request as we are going to setup a Github Workflow to run the commitchecker against each PR to validate this .

**Pull request closed without merging**
